include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [build/**]
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    - always_specify_types
    - avoid_dynamic_calls
    - prefer_typing_uninitialized_variables