--- Pré --- 


--- SQL ---
CREATE TABLE IF NOT EXISTS rot10 (rot10id SERIAL NOT NULL, CONSTRAINT rot10pk PRIMARY KEY(rot10id));

ALTER TABLE rot10 ADD COLUMN IF NOT EXISTS rot10email VARCHAR(100) ;
UPDATE rot10 SET rot10email = ' ' WHERE rot10email IS NULL;
ALTER TABLE rot10 ALTER COLUMN rot10email SET NOT NULL;

ALTER TABLE rot10 ADD COLUMN IF NOT EXISTS rot10senha VARCHAR(250) ;
UPDATE rot10 SET rot10senha = ' ' WHERE rot10senha IS NULL;
ALTER TABLE rot10 ALTER COLUMN rot10senha SET NOT NULL;

ALTER TABLE rot10 ADD COLUMN IF NOT EXISTS rot10token VARCHAR(300) ;

ALTER TABLE rot10 ADD COLUMN IF NOT EXISTS rot10refreshtoken VARCHAR(300) ;

ALTER TABLE rot10 ADD COLUMN IF NOT EXISTS rot10roles TEXT ;
--- Pós ---

INSERT INTO db_migration (name, time_run) VALUES ('R_00001.sql', NOW());
