--- Pré --- 


--- SQL ---
CREATE TABLE IF NOT EXISTS cgl29 (cgl29id SERIAL NOT NULL, CONSTRAINT cgl29pk PRIMARY KEY(cgl29id));
CREATE TABLE IF NOT EXISTS cgl30 (cgl30id SERIAL NOT NULL, CONSTRAINT cgl30pk PRIMARY KEY(cgl30id));
CREATE TABLE IF NOT EXISTS cgl65 (cgl65id SERIAL NOT NULL, CONSTRAINT cgl65pk PRIMARY KEY(cgl65id));

ALTER TABLE cgl29 ADD COLUMN IF NOT EXISTS cgl29nome VARCHAR(50) ;
UPDATE cgl29 SET cgl29nome = ' ' WHERE cgl29nome IS NULL;
ALTER TABLE cgl29 ALTER COLUMN cgl29nome SET NOT NULL;

DROP INDEX IF EXISTS cgl29_uk;
CREATE UNIQUE INDEX cgl29_uk ON cgl29 (COALESCE(cgl29nome, ' '));
DROP INDEX IF EXISTS cgl29_mk;
CREATE INDEX cgl29_mk ON cgl29 (cgl29nome);

ALTER TABLE cgl30 ADD COLUMN IF NOT EXISTS cgl30autenticacao BIGINT ;
UPDATE cgl30 SET cgl30autenticacao = 0 WHERE cgl30autenticacao IS NULL;
ALTER TABLE cgl30 ALTER COLUMN cgl30autenticacao SET NOT NULL;

ALTER TABLE cgl30 ADD COLUMN IF NOT EXISTS cgl30nome VARCHAR(30) ;
UPDATE cgl30 SET cgl30nome = ' ' WHERE cgl30nome IS NULL;
ALTER TABLE cgl30 ALTER COLUMN cgl30nome SET NOT NULL;

ALTER TABLE cgl30 ADD COLUMN IF NOT EXISTS cgl30empativa BIGINT ;
ALTER TABLE cgl30 ALTER COLUMN cgl30empativa SET NOT NULL;

ALTER TABLE cgl30 ADD COLUMN IF NOT EXISTS cgl30credencial BIGINT ;
ALTER TABLE cgl30 ALTER COLUMN cgl30credencial SET NOT NULL;

DROP INDEX IF EXISTS cgl30_uk;
CREATE UNIQUE INDEX cgl30_uk ON cgl30 (COALESCE(cgl30autenticacao, 0));
DROP INDEX IF EXISTS cgl30_mk;
CREATE INDEX cgl30_mk ON cgl30 (cgl30autenticacao);

ALTER TABLE cgl65 ADD COLUMN IF NOT EXISTS cgl65cnpj VARCHAR(14) ;
UPDATE cgl65 SET cgl65cnpj = ' ' WHERE cgl65cnpj IS NULL;
ALTER TABLE cgl65 ALTER COLUMN cgl65cnpj SET NOT NULL;

ALTER TABLE cgl65 ADD COLUMN IF NOT EXISTS cgl65nome VARCHAR(100) ;
UPDATE cgl65 SET cgl65nome = ' ' WHERE cgl65nome IS NULL;
ALTER TABLE cgl65 ALTER COLUMN cgl65nome SET NOT NULL;

DROP INDEX IF EXISTS cgl65_uk;
CREATE UNIQUE INDEX cgl65_uk ON cgl65 (COALESCE(cgl65cnpj, ' '));
DROP INDEX IF EXISTS cgl65_mk;
CREATE INDEX cgl65_mk ON cgl65 (cgl65cnpj);
DO $$ BEGIN BEGIN  ALTER TABLE cgl30 ADD CONSTRAINT cgl30empativa_cgl65_FK FOREIGN KEY (cgl30empativa) REFERENCES cgl65 (cgl65id) ON DELETE NO ACTION ;  EXCEPTION WHEN duplicate_object THEN RAISE NOTICE 'Constraint already exists, command ignored';  END; END $$;
DO $$ BEGIN BEGIN  ALTER TABLE cgl30 ADD CONSTRAINT cgl30credencial_cgl29_FK FOREIGN KEY (cgl30credencial) REFERENCES cgl29 (cgl29id) ON DELETE NO ACTION ;  EXCEPTION WHEN duplicate_object THEN RAISE NOTICE 'Constraint already exists, command ignored';  END; END $$;
--- Pós ---

INSERT INTO db_migration (name, time_run) VALUES ('V_00002.sql', NOW());
