--- Pré --- 
CREATE TABLE IF NOT exists  db_migration(name VARCHAR(20) NOT NULL PRIMARY KEY, time_run timestamp not null);

--- SQL ---
CREATE TABLE IF NOT EXISTS rot01 (rot01id SERIAL NOT NULL, CONSTRAINT rot01pk PRIMARY KEY(rot01id));
CREATE TABLE IF NOT EXISTS rot10 (rot10id SERIAL NOT NULL, CONSTRAINT rot10pk PRIMARY KEY(rot10id));

ALTER TABLE rot01 ADD COLUMN IF NOT EXISTS rot01cnpj VARCHAR(14) ;
UPDATE rot01 SET rot01cnpj = ' ' WHERE rot01cnpj IS NULL;
ALTER TABLE rot01 ALTER COLUMN rot01cnpj SET NOT NULL;

ALTER TABLE rot01 ADD COLUMN IF NOT EXISTS rot01rs VARCHAR(100) ;
UPDATE rot01 SET rot01rs = ' ' WHERE rot01rs IS NULL;
ALTER TABLE rot01 ALTER COLUMN rot01rs SET NOT NULL;

ALTER TABLE rot01 ADD COLUMN IF NOT EXISTS rot01tenant VARCHAR(20) ;
UPDATE rot01 SET rot01tenant = ' ' WHERE rot01tenant IS NULL;
ALTER TABLE rot01 ALTER COLUMN rot01tenant SET NOT NULL;

DROP INDEX IF EXISTS rot01_uk;
CREATE UNIQUE INDEX rot01_uk ON rot01 (COALESCE(rot01cnpj, ' '));
DROP INDEX IF EXISTS rot01_mk;
CREATE INDEX rot01_mk ON rot01 (rot01cnpj);

DROP INDEX IF EXISTS rot01_uk1;
CREATE UNIQUE INDEX rot01_uk1 ON rot01 (COALESCE(rot01tenant, ' '));
DROP INDEX IF EXISTS rot01_mk1;
CREATE INDEX rot01_mk1 ON rot01 (rot01tenant);

ALTER TABLE rot10 ADD COLUMN IF NOT EXISTS rot10contrato BIGINT ;
ALTER TABLE rot10 ALTER COLUMN rot10contrato SET NOT NULL;

ALTER TABLE rot10 ADD COLUMN IF NOT EXISTS rot10email VARCHAR(100) ;
UPDATE rot10 SET rot10email = ' ' WHERE rot10email IS NULL;
ALTER TABLE rot10 ALTER COLUMN rot10email SET NOT NULL;

ALTER TABLE rot10 ADD COLUMN IF NOT EXISTS rot10senha VARCHAR(250) ;
UPDATE rot10 SET rot10senha = ' ' WHERE rot10senha IS NULL;
ALTER TABLE rot10 ALTER COLUMN rot10senha SET NOT NULL;

ALTER TABLE rot10 ADD COLUMN IF NOT EXISTS rot10token VARCHAR(300) ;

ALTER TABLE rot10 ADD COLUMN IF NOT EXISTS rot10refreshtoken VARCHAR(300) ;

ALTER TABLE rot10 ADD COLUMN IF NOT EXISTS rot10roles TEXT ;

DROP INDEX IF EXISTS rot10_uk;
CREATE UNIQUE INDEX rot10_uk ON rot10 (COALESCE(rot10email, ' '));
DROP INDEX IF EXISTS rot10_mk;
CREATE INDEX rot10_mk ON rot10 (rot10email);
DO $$ BEGIN BEGIN  ALTER TABLE rot10 ADD CONSTRAINT rot10contrato_rot01_FK FOREIGN KEY (rot10contrato) REFERENCES rot01 (rot01id) ON DELETE NO ACTION ;  EXCEPTION WHEN duplicate_object THEN RAISE NOTICE 'Constraint already exists, command ignored';  END; END $$;
--- Pós ---

INSERT INTO db_migration (name, time_run) VALUES ('R_00001.sql', NOW());
